# Setup
locale: ko-KR
timezone: Asia/Seoul
title: songsongpa's blog
tagline: ""
description: "개발 및 공부 블로그"
url: "https://songsongpa.github.io"
baseurl: ""
paginate: 10
permalink: pretty

# About/contact
author:
  name: songsongpa
  url:
  email: songsongpa0322@gmail.com

github:
  username: songsongpa
  repo: https://github.com/songsongpa?tab=repositories

# Gems
plugins:
  - jekyll-paginate

exclude:
  - vendor
  - Gemfile.lock
  - Gemfile
  - tools
  - docs
  - README.md
  - LICENSE
